export const USER_LOGGED_IN = 'LOGIN_USER_SUCCESS';
export const USER_LOGGED_OUT = 'LOGOUT_USER';
export const AUTH_USER_SESSION_EXPIRED = 'AUTH_USER_SESSION_EXPIRED';
export const AUTH_LOGIN_CODE_RECEIVED = 'AUTH_LOGIN_CODE_RECEIVED';
export const USER_AUTHORIZED = 'USER_AUTHORIZED';
export const PARTICIPANT_SELECTED = 'PARTICIPANT_SELECTED';
export const HAS_INCOMPLETE_OPERATION = 'HAS_INCOMPLETE_OPERATION';
export const INSURER_SELECTED = 'INSURER_SELECTED';
export const AUTH_STARTED = 'AUTH_STARTED';
export const AUTH_USER_DATA_LOADING = 'AUTH_USER_DATA_LOADING';
export const AUTH_USER_DATA_FAILED = 'AUTH_USER_DATA_FAILED';
export const LANGUAGE_CHANGED = 'LANGUAGE_CHANGED';

export const OPERATION_FILE_UPLOADED = 'OPERATION_FILE_UPLOADED';
export const SYSTEM_LANGUAGES_LOADED = 'SYSTEM_LANGUAGES_LOADED';


export const TAB_OPENED = 'TAB_OPENED';
export const TAB_CLOSED = 'TAB_CLOSED';


export const SHOW_REQUEST_ERROR = 'SHOW_REQUEST_ERROR';
export const CLOSE_REQUEST_ERROR = 'CLOSE_REQUEST_ERROR';


export const PRODUCT_UNAPPROVED_COUNT_LOADED = "PRODUCT_UNAPPROVED_COUNT_LOADED"
export const PRODUCT_UNAPPROVED_COUNT_LOADING = "PRODUCT_UNAPPROVED_COUNT_LOADING"



